name: Build Docker Image for CoppeliaSim EDU
on: [push, workflow_dispatch]

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build_image:
    name: Build Docker Image for ${{env.BRANCH_NAME}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push CoppeliaSim for ${{env.BRANCH_NAME}}
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          file: coppeliasim/Dockerfile
          tags: | 
              ${{ vars.DOCKER_USERNAME }}/coppeliasim:${{env.BRANCH_NAME}}